In [27]:
import pandas as pd

In [28]:
x = pd.DataFrame([['a', 'b'], ['c', 'd']], columns=['letter', 'number'])
y = pd.DataFrame([['a', '1'], ['c', '2'], ['e', 3]], columns=['letter', 'number'])

In [34]:
z = x.merge(y, left_on='letter', right_on='letter', how='inner')
z

       number_x number_y
letter
a             b        1
c             d        2

In [29]:
x = x.set_index('letter')
x

       number
letter
a           b
c           d

In [30]:
y = y.set_index('letter')
y

       number
letter
a           1
c           2
e           3