In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/hpc/projects/theory_ds/internship/jacob.paras/matrices/countsTable.csv')

In [3]:
df

,GeneID,SRR12786066,SRR21228035,SRR22443586,ERR963178,ERR1889732,SRR6020318,SRR12287377,SRR6654404,SRR13242476,...,SRR6469776,SRR6652906,SRR9728720,SRR11302739,SRR6908622,SRR6025604,SRR14066777,SRR4242454,ERR1204598,SRR14567464
0,ENSDARG00000000001,96,118,250,0,8,0,75,0,71,...,0,92,83,0,0,0,0,11,0,13
1,ENSDARG00000000002,1,123,47,14,0,0,66,0,10,...,0,51,147,0,0,0,0,41,17,0
2,ENSDARG00000000018,471,489,472,5,2,0,3762,0,1288,...,12,269,1155,0,0,10,0,87,8,786
3,ENSDARG00000000019,4720,1152,1060,33,0,0,1193,167,1750,...,0,968,895,1,0,12,0,61,63,1827
4,ENSDARG00000000068,380,204,483,2,9,0,202,64,301,...,0,102,687,13,0,0,0,71,1,1033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32520,__no_feature,1854925,3396845,2741622,106074,16723,48,3903180,46397,1373831,...,181483,11331868,944195,28957,3373,11431909,25199,456959,146970,4081684
32521,__ambiguous,206868,83131,131081,1348,3843,0,470233,6057,116282,...,3582,74941,382663,10378,66,300875,9204,122823,2556,1040368
32522,__too_low_aQual,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32523,__not_aligned,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32524,__alignment_not_unique,533033,1083183,4110099,57346,10906,11,1402686,36842,664980,...,37816,1217509,2093780,27078,1768,1393959,8805,609820,93592,860999

In [4]:
df_new = df.set_index('GeneID')
df_new

,SRR12786066,SRR21228035,SRR22443586,ERR963178,ERR1889732,SRR6020318,SRR12287377,SRR6654404,SRR13242476,SRR11922999,...,SRR6469776,SRR6652906,SRR9728720,SRR11302739,SRR6908622,SRR6025604,SRR14066777,SRR4242454,ERR1204598,SRR14567464
GeneID,,,,,,,,,,,,,,,,,,,,,
ENSDARG00000000001,96,118,250,0,8,0,75,0,71,258,...,0,92,83,0,0,0,0,11,0,13
ENSDARG00000000002,1,123,47,14,0,0,66,0,10,31,...,0,51,147,0,0,0,0,41,17,0
ENSDARG00000000018,471,489,472,5,2,0,3762,0,1288,554,...,12,269,1155,0,0,10,0,87,8,786
ENSDARG00000000019,4720,1152,1060,33,0,0,1193,167,1750,3148,...,0,968,895,1,0,12,0,61,63,1827
ENSDARG00000000068,380,204,483,2,9,0,202,64,301,1125,...,0,102,687,13,0,0,0,71,1,1033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
__no_feature,1854925,3396845,2741622,106074,16723,48,3903180,46397,1373831,945397,...,181483,11331868,944195,28957,3373,11431909,25199,456959,146970,4081684
__ambiguous,206868,83131,131081,1348,3843,0,470233,6057,116282,104540,...,3582,74941,382663,10378,66,300875,9204,122823,2556,1040368
__too_low_aQual,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
__not_aligned,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
__alignment_not_unique,533033,1083183,4110099,57346,10906,11,1402686,36842,664980,384324,...,37816,1217509,2093780,27078,1768,1393959,8805,609820,93592,860999

In [5]:
df_new = df_new.drop(['__ambiguous', '__too_low_aQual', '__not_aligned'])
df_new

,SRR12786066,SRR21228035,SRR22443586,ERR963178,ERR1889732,SRR6020318,SRR12287377,SRR6654404,SRR13242476,SRR11922999,...,SRR6469776,SRR6652906,SRR9728720,SRR11302739,SRR6908622,SRR6025604,SRR14066777,SRR4242454,ERR1204598,SRR14567464
GeneID,,,,,,,,,,,,,,,,,,,,,
ENSDARG00000000001,96,118,250,0,8,0,75,0,71,258,...,0,92,83,0,0,0,0,11,0,13
ENSDARG00000000002,1,123,47,14,0,0,66,0,10,31,...,0,51,147,0,0,0,0,41,17,0
ENSDARG00000000018,471,489,472,5,2,0,3762,0,1288,554,...,12,269,1155,0,0,10,0,87,8,786
ENSDARG00000000019,4720,1152,1060,33,0,0,1193,167,1750,3148,...,0,968,895,1,0,12,0,61,63,1827
ENSDARG00000000068,380,204,483,2,9,0,202,64,301,1125,...,0,102,687,13,0,0,0,71,1,1033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSDARG00000117825,0,0,0,0,0,0,2,0,0,0,...,0,33,0,0,0,0,0,0,0,1
ENSDARG00000117826,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
ENSDARG00000117827,0,4,0,0,0,0,1,0,0,0,...,0,2,0,0,0,0,0,0,0,0
__no_feature,1854925,3396845,2741622,106074,16723,48,3903180,46397,1373831,945397,...,181483,11331868,944195,28957,3373,11431909,25199,456959,146970,4081684
__alignment_not_unique,533033,1083183,4110099,57346,10906,11,1402686,36842,664980,384324,...,37816,1217509,2093780,27078,1768,1393959,8805,609820,93592,860999

In [10]:
df_out = pd.DataFrame()
df_out['reads'] = df_new[df_new.columns].sum()

In [11]:
df_out.index.name = 'GeneID'
df_out

                reads
GeneID
SRR12786066  22072334
SRR21228035  15863543
SRR22443586  67140410
ERR963178      277430
ERR1889732     108998
...               ...
SRR6025604   32410656
SRR14066777     95936
SRR4242454   10362907
ERR1204598     525942
SRR14567464  32065239

[54179 rows x 1 columns]

In [13]:
df_out.to_csv('../zf_counts.csv')